AdaCore/libadalang

utils/travis-script.sh
This will hopefully avoid out of memory errors when building the
generated quex_lexer.c unit.
=> Restrict build parallelism for Travis CI

ada/language/ast.py, ada/testsuite/tests/ada_api/foreign_nodes/test.out
This is done by making them subclasses of `BaseSubpBody` instead of `ClassicSubpDecl`.
This makes them work the same as `ExprFunction`.
This makes conceptual sense, since they work the same way as a normal `SubpBody`: they can declare a subprogram or complete a previous declaration.
Fixes #195.
=> Make SubpRenamingDecl and NullSubpDecl resolve their corresponding decl

ada/language/ast.py, ada/testsuite/tests/python/unique_identifying_name/test.adb, ada/testsuite/tests/python/unique_identifying_name/test.ads, ada/testsuite/tests/python/unique_identifying_name/test.out, ada/testsuite/tests/python/unique_identifying_name/test.py, ada/testsuite/tests/python/unique_identifying_name/test.yaml
So far we only considered subprogram decls, not bodies, so
unique_identifying_name for subp bodies was not computed correctly.
Also the uit for EnumLitSynthTypeExpr was not computed correctly.
Add test for all different known cases.
=> S215-003: Fix bug in BasicDecl.unique_iname

ada/testsuite/testsuite_support/__init__.py
optparse materializes missing options with action='store_true' as None
values, unlike argparse which materializes them as False. Canonicalize
to booleans to preserve assumptions in options processing.
=> Fix testsuite regressions after recent refactoring

.travis.yml, utils/travis-install.sh
With GNAT Community 2019 gnatcoll-bindings is unable to fine gmp.h
in /usr/local/include, where GMP is installed on Travis. Set CPATH
fixes this.
=> Fix Travis CI on MacOS X

ada/language/ast.py, ada/testsuite/tests/name_resolution/S902-009/root-p.adb, ada/testsuite/tests/name_resolution/S902-009/root-p.ads, ada/testsuite/tests/name_resolution/S902-009/root.ads, ada/testsuite/tests/name_resolution/S902-009/test.adb, ada/testsuite/tests/name_resolution/S902-009/test.out, ada/testsuite/tests/name_resolution/S902-009/test.yaml
Minimal lookups are sufficient here because the next part should be
in the same environment. This also prevents finding back the original
node when doing an env lookup on the package's body (since a package
declaration is the parent of its body).
An alternative could have been to filter out the results that are
equivalent to Entity, but it seems cleaner that way.
=> S902-009: Fix next_part.

ada/language/ast.py
While removing the p_unit_body property as part of the
"multiple units per file" patch, I made an error while copying its
logic in the p_basic_decl_next_part_for_decl property by discarding
the case where the enclosing compilation unit is a Body, in which
the "body unit" is simply itself.
This was causing a weird error in the ALS because it ended up fetching
the "body unit" in another file.
=> R219-008: Fix erroneous refactoring.

ada/extensions/src/libadalang-expr_eval.adb, ada/testsuite/tests/ada_api/static_expr_eval/test.adb, ada/testsuite/tests/ada_api/static_expr_eval/test.out
P_Canonical_Type was used instead. This is wrong if a hierarchy of
subtypes with multiple ranges is defined.
=> SC18-041 Eval_Range_Attr use P_Designated_Type_Decl for Subtype_Decl

ada/language/lexer.py
The concrete syntax for lexers allows defining multiple rules to produce a token
by using the `or(...)` construct. There is however a loss of expressivity because
there can't be any interleaving rule between the alternatives.
With this new restriction in place, libadalang's lexer could not be correctly
unparsed, because some tokens (Integer and Decimal) were produced by multiple
rules that were not consecutive, and therefore not translatable to an `or(...)`
construct.
This fix is simply to reorder them (which should not impact anything) so
as to allow a correct translation to the new concrete syntax.
=> RA22-015: Fix token declaration order for the concrete syntax.

.gitignore
I use `lktl` as a shortcut symlink to liblktlang’s spec.
=> .gitignore: add the lktl shortcut

ada/language/ast.py, ada/testsuite/tests/properties/is_visible/pkg.ads, ada/testsuite/tests/properties/is_visible/pkg_g.ads, ada/testsuite/tests/properties/is_visible/test.out, ada/testsuite/tests/properties/is_visible/test.yaml
In most cases, what we really want is the GenericPackageDecl, not the
GenericPackageInternal. Note that semantic_parent can still be used for that.
=> T212-032: Never return Generic_*_Internal nodes from Parent_Basic_Decl.

ada/extensions/src/libadalang-implementation-extensions.adb, ada/testsuite/tests/properties/find_all_references/a-child.adb, ada/testsuite/tests/properties/find_all_references/test.out, ada/testsuite/tests/properties/find_all_references/test.yaml, user_manual/changes/T510-001.yaml
In particular, use the recently introduced p_imported_units property to
discover "with"ed units. This removes a duplicate logic we had for discovering
those, and removes a bug where body-only top-level subprograms defined as child
packages would be erroneously filtered by p_filter_is_imported_by.
=> T510-001: Rework filter_is_imported_by.

ada/extensions/python, ada/testsuite/tests/properties/python_doc_name/test.adb, ada/testsuite/tests/properties/python_doc_name/test.out, ada/testsuite/tests/properties/python_doc_name/test.yaml
Not implemented in Libadalang proper due to missing DSL features in
langkit.
Also remove python methode Name.full_name, not useful in the current
state of things.
=> T513-013: Implement python method Name.doc_name

ada/testsuite/ada/nameres.adb, utils/nameres.gpr
When --time is passed, report the total time at end of processing.
Add a switch --memory which will print the memory footprint at
the end of processing.
=> T811-021 nameres: improve resources reporting

ada/language/ast.py, ada/testsuite/tests/name_resolution/requeue_stmt/test.out, ada/testsuite/tests/name_resolution/requeue_stmt/test_requeue.adb
An assumption was previously made during the construction of requeue
statements' equations that the requeued name should reference an EntryDecl,
thus filtering off entry bodies.
This was not a problem until recent improvements made on entry navigation
(done under this ticket), where entry bodies were now added to lexical
envs and became thus visible. This fix consists in not binding twice the
requeued name.
The simple change in the test consists in moving the body of the
requeued entry such that it is visible at the site of the requeue stmt.
This shows that even though the entry body is visible, the requeue stmt
is correctly resolved.
=> T706-023: Fix requeue stmt equation.

ada/extensions/src/libadalang-helpers.adb, ada/extensions/src/libadalang-helpers.ads, ada/testsuite/tests/ada_api/app/recursive/main.adb, ada/testsuite/tests/ada_api/app/recursive/p.gpr, ada/testsuite/tests/ada_api/app/recursive/sub/hello.adb, ada/testsuite/tests/ada_api/app/recursive/sub/q.gpr, ada/testsuite/tests/ada_api/app/recursive/test.out, ada/testsuite/tests/ada_api/app/recursive/test.yaml
When this flag is set, all sources in the project tree are processed,
rather than only the sources of the root project.
As a side effect, this behavior becomes available in the nameres program.
=> T813-011 Add a -U/--recursive option to Helpers

ada/extensions/src/libadalang-helpers.adb, ada/extensions/src/libadalang-helpers.ads, ada/testsuite/tests/ada_api/app/runtime/main.adb, ada/testsuite/tests/ada_api/app/runtime/p.gpr, ada/testsuite/tests/ada_api/app/runtime/test.out, ada/testsuite/tests/ada_api/app/runtime/test.yaml
Add support for processing the runtime file through a new
--process-runtime option.
(This also processes any "predefined sources", as there is no
distinction between those and the runtime in the current project API).
=> T831-043 Libadalang.Helpers: add support for processing runtime

.github/workflows/build-binaries.yml, utils/gh-build-binaries.sh
* Uninstall gnatcoll and gpr from gnat CE 2020 to avoid conflicts
* Mount /opt dir on windows and use it for ADALIB_DIR. This way
msys2 and native path to this directory match.
* Don't build relocatable libraries, because they crash builds TC11_054
* Use oldes version of Mac OS and Ubuntu to keep compatibility with
older system
* Upload to newer version on BinTray, because older one has locked.
Also change archive file names to avoid conflicts with locked
files.
* Upgrade to upload-bintray-action@v4. It will auto-create a version
before uploading.
=> TC07-049 Fix the script to build binaries

utils/gh-build-binaries.sh
Make `gprinstall --uninstall` optional, because the install dir is
cached, so gnatcoll/gpr could be uninstalled.
Drop extra spaces.
=> Fix GitHub Action for build binaries.

extensions/ocaml_api/unit_providers/module_struct
The C strings allocated to represent the list of files in the project
were garbage-collected too aggressively by the GC, resulting in memory
corruption. Switch to a version of the code where we keep more GC roots.
Also explicitly set the last element of the array passed to LAL
to NULL. It is not clear this was done implicitly by Ctypes.
=> U219-050 fix memory corruption in OCaml binding for auto_provider

ada/ast.py, testsuite/tests/navigation/resolve_generic_subp/test.adb, testsuite/tests/navigation/resolve_generic_subp/test.out, testsuite/tests/navigation/resolve_generic_subp/test.py, testsuite/tests/navigation/resolve_generic_subp/test.yaml, user_manual/changes/U601-009.yaml
The previous implementation of resolve_generic_actual was using env_elements
when resolving a subprogram actual, but env_elements_baseid performs filtering
as if the subprogram was used in a call, and thus would exclude all non-paramless
subprograms. We now use all_env_elements instead.
=> U601-009: Fix erroneous filtering of generic actuals.

.github/workflows/build-binaries.yml
Latest changes in libgpr break compability with GNAT CE 2020,
but on MacOS X we don't have any newer compiler for now.
We revert this commit in libgpr before build it on Mac OS.
=> Restore binaries compilation on MacOS X.

ada/ast.py, testsuite/tests/name_resolution/non_visible_dependency/foo.ads, testsuite/tests/name_resolution/non_visible_dependency/test.adb, testsuite/tests/name_resolution/non_visible_dependency/test.out, testsuite/tests/name_resolution/non_visible_dependency/test.yaml
Where we did treat missing the spec of a library level subp body as an
error/missing dependency.
=> U712-008: fix forgotten case

ada/grammar.py, testsuite/tests/parser/null_abstract_state/input, testsuite/tests/parser/null_abstract_state/test.out, testsuite/tests/parser/null_abstract_state/test.yaml
`null` is a valid abstract state value
=> U727-022: Fix parsing bug in `Abstract_State`

ada/ast.py, testsuite/tests/properties/complete/test.out, testsuite/tests/properties/complete/testcomp.adb
In particular visibility checks in "defining_env" are bypassed, so that
you can go fetch items in a package that you haven't withed.
=> U805-033: p_complete returns more non-visible symbols

ada/ast.py, user_manual/changes/U823-021.yaml
Also document the fact that all this code is strictly wrong, but this
has no known impact on LAL at the moment, since we only pledge to give
good results on legal code.
=> U823-021: Fix library level generic subprograms visibilty

extensions/ocaml_api/unit_providers/module_struct
Based on what we found in Ctypes discussions [1, 2, 3], and what we
observed in practice using Valgrind, the OCaml lifetime for the C
strings containing the names of the files in the project for an auto
provider is too short. The garbage collector can collect those strings
before the function create_auto_provider has fully ran.
We correct this by forcing the cstrings local variable to be live accross
the entire call, and even further: it won't be collected until the
finalizer for the the UnitProvider runs. In practice, this eliminates
all the problems we've been able to see with Valgrind.
[1] https://github.com/ocamllabs/ocaml-ctypes/issues/476
[2] https://github.com/ocamllabs/ocaml-ctypes/issues/571
[3] http://lists.ocaml.org/pipermail/ctypes/2018-March/000276.html
=> U219-050 fix more memory corruption problems with UnitProvider binding

ada/ast.py, testsuite/tests/properties/get_pragma_component/test.adb, testsuite/tests/properties/get_pragma_component/test.out, testsuite/tests/properties/get_pragma_component/test.yaml
We were wrongly assuming that a pragma would always apply to a `BasicDecl` lying
in a `DeclarativePart`, which is not necessarily the case, for example with
`ComponentDecl`s (components of a record).
=> U913-015: Fix lookup scope for pragma resolution.

ada/ast.py
Remove 's' which breaks highlighting after a double-quoted string.
Fix English typo.
=> U623-025 Fix bad highlighting in generated HTML

.github/workflows/build-binaries.yml
GitHub doesn't provide ubuntu-16.04 "runner" any more. Let's
switch to oldest available (ubuntu-18.04).
=> Swith CI to use ubuntu-18.04

ada/ast.py, testsuite/tests/name_resolution/synthetic_neq/test.adb, testsuite/tests/name_resolution/synthetic_neq/test.out
This is done by reworking how implicit `/=` operators are handled. In particular,
we remove the special casing done it operator name resolution and instead rely and
lexical environments only, by adding an entry for the `/=` operator whenever we
have to add an entry for a user-defined `=` operator.
This is therefore a nice cleanup.
=> U918-003: Fix name resolution of implicit `/=` operator.

.github/workflows/build-binaries.yml, utils/gh-build-binaries.sh
and get rid of outdated GNAT CE 2020 for Mac OS
=> Use GCC 11 toolchain by alire

ada/ast.py, testsuite/tests/name_resolution/invalid_UA25-009/test.adb, testsuite/tests/name_resolution/invalid_UA25-009/test.out, testsuite/tests/name_resolution/invalid_UA25-009/test.yaml
My changes for TA29-030 made LAL crash with an Assertion_Error (or worst in
production builds) when given the code pattern presented in the test case attached
to this commit: a parameter's type has the same name as the parameter itself. Note
that this is not valid Ada, however LAL shouldn't choke on it! This commit
resolves the issue.
=> UA25-009: Fix regression on invalid code.

ada/ast.py, testsuite/tests/name_resolution/builtin_binop/test.out, testsuite/tests/name_resolution/contract_pre_2/test.adb, testsuite/tests/name_resolution/contract_pre_2/test.out, testsuite/tests/name_resolution/contract_pre_2/test.yaml, testsuite/tests/name_resolution/operators_6/test.out, testsuite/tests/name_resolution/record_rep_clause/test.out, testsuite/tests/properties/inherited_primitives/test.out, testsuite/tests/properties/is_inherited_primitive/test.out
The main reason is that it is causing trouble in some tools that don't expect
SyntheticSubpDecl nodes to be returned here. Besides I also think it makes more
sense not to output them by default.
=> UB16-053: Various fixes

ada/ast.py, ada/grammar.py, testsuite/tests/ada_api/dump/test.out, testsuite/tests/name_resolution/iterated_component_association/iterassoc_filter.adb, testsuite/tests/name_resolution/iterated_component_association/test.out, testsuite/tests/name_resolution/iterated_component_association/test.yaml, testsuite/tests/parser/expression_5/test.out, testsuite/tests/parser/for_loop_parameter_spec_0/test.out, testsuite/tests/parser/for_loop_parameter_spec_1/test.out, testsuite/tests/parser/loop_statement_0/test.out, testsuite/tests/parser/loop_statement_1/test.out, user_manual/changes/UB16-009.yaml
This patch implements the iterator_filter feature introduced in Ada
2022, AI12-0250.
TN: UB16-009
=> Add Ada 2022 iterator_filter support for iterator specification

ada/ast.py, testsuite/tests/name_resolution/index_attr/test.out, user_manual/changes/UC02-047.yaml
This change fixes the xref_equation for `EntrySpec` name resolution.
TN: UC02-047
=> Fix `EntrySpec` xref_equation

testsuite/tests/name_resolution/default_initial_condition/dic.ads, testsuite/tests/name_resolution/default_initial_condition/test.out, testsuite/tests/name_resolution/default_initial_condition/test.yaml
As already supported by libadalang, this patch only adds some tests
for the `Default_Initial_Condition` aspect, introduced by the Ada 2022
standard.
See also:
http://www.ada-auth.org/cgi-bin/cvsweb.cgi/ai12s/ai12-0265-1.txt.
TN: V103-013
=> Add `Default_Initial_Condition` aspect nameres tests

ada/ast.py, testsuite/tests/properties/is_constant_object/pack.adb, testsuite/tests/properties/is_constant_object/pack.ads, testsuite/tests/properties/is_constant_object/test.out, testsuite/tests/properties/is_constant_object/test.yaml
This fix adds a missing case for the ``is_constant_object`` property
where a call expression refers to a subprogram without specification.
TN: V107-027
=> Fix ``is_constant_object`` property

testsuite/tests/properties/get_has_aspect_param_spec/aspec.adb, testsuite/tests/properties/get_has_aspect_param_spec/test.out, testsuite/tests/properties/get_has_aspect_param_spec/test.yaml
This patch just adds some tests for the Ada 2022 feature allowing
aspect specifications on formal parameters.
See: http://www.ada-auth.org/cgi-bin/cvsweb.cgi/ai12s/ai12-0395-1.txt.
TN: V112-031
=> Add tests for aspect specifications on formal parameters

ada/ast.py, ada/grammar.py, testsuite/tests/lexical_envs/records/test.out, testsuite/tests/parser/discriminant_part_1/test.out, testsuite/tests/parser/full_type_decl_3/test.out, testsuite/tests/parser/full_type_decl_4/test.out, testsuite/tests/parser/full_type_decl_7/test.out, testsuite/tests/parser/type_decl_0/test.out, testsuite/tests/properties/aspect_spec_most_decls/aspec.adb, testsuite/tests/properties/aspect_spec_most_decls/test.out, testsuite/tests/properties/aspect_spec_most_decls/test.yaml, user_manual/changes/V112-052.yaml
As stated by the 2022 Ada standard revision, this new feature allows
aspect specifications on most declarations. It concerns extended
return object declarations, discriminant specifications, and entry
index specifications.
See: http://www.ada-auth.org/cgi-bin/cvsweb.cgi/ai12s/ai12-0398-1.txt.
TN: V112-052
=> Most declarations allows aspect specifications

utils/gh-build-binaries.sh
described in the ALS repo
[#857](https://github.com/AdaCore/ada_language_server/issues/875).
=> Drop unneeded C sources to fix Mac OS compat issue

contrib/detect_copy_paste_sa.py
This made this code usable in python 3.
Before it crashed by not truncating on division, or by the use of .itervalues instead of .values.
This is to comply with the python 3 enhancement proposed in 2019.
Also, the link to the CLA is broken, in the contributing guidelines.
_The first time you want to contribute a patch on the AdaCore GitHub, we ask you to electronically approve our Individual Contributor Licence Agreement. CLA assistant will send you a link on your GitHub pull request to do so._
Cheers.
=> Minimal update to python 3

testsuite/tests/name_resolution/bracket_aggregate/nag.adb, testsuite/tests/name_resolution/bracket_aggregate/test.out, testsuite/tests/name_resolution/bracket_aggregate/test.yaml
As per proposal made in the following AI:
http://www.ada-auth.org/cgi-bin/cvsweb.cgi/ai12s/ai12-0306-1.txt.
TN: V113-030
=> Add nameres tests for bracket aggregates

ada/ast.py, testsuite/tests/properties/inherited_primitives_2/pkg-der.adb, testsuite/tests/properties/inherited_primitives_2/pkg-der.ads, testsuite/tests/properties/inherited_primitives_2/pkg.adb, testsuite/tests/properties/inherited_primitives_2/pkg.ads, testsuite/tests/properties/inherited_primitives_2/test.out, testsuite/tests/properties/inherited_primitives_2/test.yaml
This fixes a regression introduced by the previous change on this ticket. I added a regression test for that.
=> V106-029: Compare the canonical representations of types.

ada/ast.py, ada/grammar.py, testsuite/tests/name_resolution/access_def_subtype_indication/iter.adb, testsuite/tests/name_resolution/access_def_subtype_indication/test.out, testsuite/tests/name_resolution/access_def_subtype_indication/test.yaml, user_manual/changes/V104-011.yaml
This patch adds support for access definition in loop parameter
subtype indication, as part of the Ada 2022 feature defined by
AI12-0156
(http://www.ada-auth.org/cgi-bin/cvsweb.cgi/ai12s/ai12-0156-1.txt).
TN: V104-011
=> Allow access definition in loop parameter subtype indication

ada/ast.py
This patch improves the documentation of `withed_units` and
`unit_dependencies` by referencing them to each other in order to give
better information to the user.
TN: U506-026
=> Improve `withed_units`/`unit_dependencies` documentation

ada/ast.py, testsuite/tests/properties/call_expr_kind/kind.adb, testsuite/tests/properties/call_expr_kind/test.out, testsuite/tests/properties/call_expr_kind/test.yaml, user_manual/changes/UC22-030.yaml
Add a new property `CallExpr.kind` to query the kind of a `CallExpr`
(call, array slice, array index, or type conversion). It returns a
`CallExprKind` enum value.
TN: UC22-030
=> Add a new property to query the kind of a CallExpr

ada/ast.py, testsuite/tests/properties/next_part_for_decl/bug-sb08-025.adb, testsuite/tests/properties/next_part_for_decl/test.out, testsuite/tests/properties/next_part_for_decl/test.yaml, user_manual/changes/sb08-025.yaml
This change fixes a bug where ``next_part_for_decl``, when called on a
``SingleTaskTypeDecl`` returns None instead of the next part of its
``SingleTaskDecl`` parent.
TN: SB08-025
=> Fix ``SingleTaskTypeDecl.next_part_for_decl``

.github/workflows/build-binaries.yml, utils/gh-build-binaries.sh
This commit also reverts 3fe78ead4951920435d958c1de0588473822caaa
"U922-009 Don't use SAL for static libraries in GH CI"
Is also reverts 7b31725fc70f01b49bcad788d625072c071fd548
"Drop unneeded C sources to fix Mac OS compat issue"
because that change doesn't help.
It also deletes a workaround for Alire bug (see `gprbuild_`).
=> V203-005 re-enable relocatable libs
