AdaCore/libadalang

- ada/language/ast.py
- ada/testsuite/c_support/utils.h
Change-Id: Ieaa3bcc327c44185f66d761a8b6bf2507d4db739
> Track call information in name res

- .travis.yml
- README.md
- utils/travis-install.sh
- utils/travis-langkit-branch.py
- utils/travis-script.sh
This public chat room provides no history to guests, making it hard to
discuss issues on several days. GitHub issues are more appropriate.
> README.md: remove the reference to the HipChat public room

- .travis.yml
- utils/bintray.json
- utils/travis-install.sh
- utils/travis-script.sh
We deploy compiled 'stable' and 'master' branches as tar.gz to
speedup compilation of dependent projects on Travis CI.
> Deploy result of compilation as archive to bintray.

- .appveyor.yml
- utils/appveyor.sh
This script builds libadalang under Windows and upload result to bintray.com
> Add appveyor script

- ada/language/ast.py
- ada/testsuite/tests/properties/accessed_type/test.adb
- ada/testsuite/tests/properties/accessed_type/test.out
- ada/testsuite/tests/properties/accessed_type/test.py
- ada/testsuite/tests/properties/accessed_type/test.yaml
> Make accessed_type public

- install-lal-and-deps.sh
- utils/travis-install.sh
- utils/travis-langkit-branch.py
Use the travis scripts, in order to more easily stay up to date with
build changes.
closes #294
> Fix the install-lal-and-deps.sh script.

- ada/language/ast.py
- changes/S905-012.yaml
> NF S905-012: Implement BaseTypeDecl.is_formal property

- utils/travis-script.sh
Fix binary archive uploading on Travis for MacOS X. We need this archive for Ada Language Server.
> (no-tn-check) Fix binary archive uploading on Travis

- ada/language/ast.py
- ada/testsuite/tests/name_resolution/separate_task_body/t-tsk.adb
- ada/testsuite/tests/name_resolution/separate_task_body/t.adb
- ada/testsuite/tests/name_resolution/separate_task_body/t.ads
- ada/testsuite/tests/name_resolution/separate_task_body/test.out
- ada/testsuite/tests/name_resolution/separate_task_body/test.yaml
- ada/testsuite/tests/navigation/separate_subp_nav/main.adb
- ada/testsuite/tests/navigation/separate_subp_nav/p-x.adb
- ada/testsuite/tests/navigation/separate_subp_nav/p.adb
- ada/testsuite/tests/navigation/separate_subp_nav/p.ads
- ada/testsuite/tests/navigation/separate_subp_nav/test.out
- ada/testsuite/tests/navigation/separate_subp_nav/test.yaml
- ada/testsuite/tests/navigation/separate_task_nav/t-tsk.adb
- ada/testsuite/tests/navigation/separate_task_nav/t.adb
- ada/testsuite/tests/navigation/separate_task_nav/t.ads
- ada/testsuite/tests/navigation/separate_task_nav/test.out
- ada/testsuite/tests/navigation/separate_task_nav/test.yaml
> Separate navigation fixes

- ada/language/ast.py
- ada/testsuite/tests/name_resolution/image_attribute/test.adb
- ada/testsuite/tests/name_resolution/image_attribute/test.out
- ada/testsuite/tests/name_resolution/image_attribute/test.yaml
- ada/testsuite/tests/name_resolution/record_variants/foo.ads
- ada/testsuite/tests/name_resolution/record_variants/test.out
All of those were found while trying to solve S917-041
> Fix various nameres issues

- ada/extensions/ocaml_api/unit_providers/module_struct
> Fix memory leaks in OCaml bindings

- ada/extensions/ocaml_api/unit_providers/module_struct
'Cannot open' feels more like a filesystem error.
> SA07-044 more generic message in case of invalid project file

- ada/language/ast.py
- ada/testsuite/tests/properties/get_volatile_aspect/test.adb
- ada/testsuite/tests/properties/get_volatile_aspect/test.out
- ada/testsuite/tests/properties/get_volatile_aspect/test.py
- ada/testsuite/tests/properties/get_volatile_aspect/test.yaml
- user_manual/changes/SB25-043.yaml
Associated entity of a pragma Volatile is the first argument.
> SB25-043 Implement name resolution for pragma Volatile

- ada/language/ast.py
- ada/testsuite/tests/properties/primitive_subp_tagged_type/foo.adb
- ada/testsuite/tests/properties/primitive_subp_tagged_type/test.out
- ada/testsuite/tests/properties/primitive_subp_tagged_type/test.yaml
- user_manual/changes/T214-020.yaml
> T214-020: Ensure p_primitive_subp_* work properly on subp bodies.

- ada/language/ast.py
- ada/testsuite/tests/properties/complete/pkg_1-child.ads
- ada/testsuite/tests/properties/complete/pkg_1-child2.ads
- ada/testsuite/tests/properties/complete/pkg_1.ads
- ada/testsuite/tests/properties/complete/test.out
- ada/testsuite/tests/properties/complete/test.yaml
- ada/testsuite/tests/properties/complete/testcomp.adb
> T422-026: add is_visible field to CompletionItem

- .github/workflows/main.yml
> Use GitHub Actions Workflow to build on Mac OS X

- .appveyor.yml
- utils/appveyor.sh
> Use Python3.8 in AppVeyor

- ada/testsuite/ada/gnat_compare/gnat_compare.adb
- ada/testsuite/ada/gnat_compare/xrefs.ads
Recent compiler is reporting:
warning: aggregate not fully initialized
> Fix compilation warning in aggregate initialization.

- user_manual/changes/process_changes.py
> Add back __future__ imports in process_changes.py

- .github/workflows/main.yml
Previous version of upload action had issues with default input values. Now it's fixed in 'v2' tag.
> Fix BinTray uploading.

- utils/libadalang.gpr.patch
- utils/mains.gpr.patch
- utils/release.sh
> New script to create a source package

- utils/gh-build-binaries.sh
because we need them for LKQL testing
> Re-enable relocatable libraries for linux

- extensions/analysis/implem_decls
- extensions/src/libadalang-implementation-extensions.adb
- testsuite/ada/nameres.adb
and increase default nameres timeout
> Fix memoization of resolve_own_names on exception

- testsuite/ada/nameres.adb
To account for corresponding changes in langkit
> U324-040: Adapt lookup cache configuration in nameres

- ada/ast.py
This was removed during the transition because RefCategories is not an
exposable type and we needed it on this property.
This change introduces an auxiliary property for internal use only that
accepts a RefCategories parameter and reverts the all_env_elements
public property to its original signature.
> T226-048: Re-expose all_env_elements.

- ada/ast.py
- testsuite/tests/navigation/homonym_base_type/test-impl.ads
- testsuite/tests/navigation/homonym_base_type/test-pkg.ads
- testsuite/tests/navigation/homonym_base_type/test.ads
- testsuite/tests/navigation/homonym_base_type/test.out
- testsuite/tests/navigation/homonym_base_type/test.yaml
- testsuite/tests/navigation/subp_use_clause/p.adb
- testsuite/tests/navigation/subp_use_clause/p.ads
- testsuite/tests/navigation/subp_use_clause/proc.adb
- testsuite/tests/navigation/subp_use_clause/test.adb
- testsuite/tests/navigation/subp_use_clause/test.out
- testsuite/tests/navigation/subp_use_clause/test.yaml
- user_manual/changes/TC28-004.yaml
- user_manual/changes/U323-012.yaml
Also fixes U323-012 and U421-013!
> TC28-004: Fix previous part on types and subprogram

- ada/ast.py
- testsuite/tests/navigation/missing_unit/ll_subp.ads
- testsuite/tests/navigation/missing_unit/no_body_generic_subp.ads
- testsuite/tests/navigation/missing_unit/no_body_subp.ads
- testsuite/tests/navigation/missing_unit/pkg.ads
- testsuite/tests/navigation/missing_unit/test.out
- testsuite/tests/navigation/missing_unit/test.yaml
Also add a test to improve coverage of the missing units machinery
> U712-008: Don't expect imported subps to have a body unit

- ada/ast.py
> Memoize p_canonical_part property

- ada/grammar.py
- testsuite/tests/name_resolution/implicit_deref_rel_op/fuand.adb
- testsuite/tests/name_resolution/implicit_deref_rel_op/fuand.ads
- testsuite/tests/name_resolution/implicit_deref_rel_op/test.out
- testsuite/tests/name_resolution/implicit_deref_rel_op/test.yaml
- testsuite/tests/parser/anonymous_type_no_aspects/input
- testsuite/tests/parser/anonymous_type_no_aspects/test.out
- testsuite/tests/parser/anonymous_type_no_aspects/test.yaml
> anonymous types can't have aspects

- ada/ast.py
- testsuite/tests/properties/accept_stmts/pkg.adb
- testsuite/tests/properties/accept_stmts/pkg.ads
- testsuite/tests/properties/accept_stmts/pkg2.adb
- testsuite/tests/properties/accept_stmts/pkg2.ads
- testsuite/tests/properties/accept_stmts/test.out
- testsuite/tests/properties/accept_stmts/test.yaml
- user_manual/changes/S916-015.yaml
This new property returns an array of accept statements calling
the entry declaration.
TN: S916-015
> Add `EntryDecl.p_accept_stmts` property

- .vscode/settings.json
mains.gpr is now in build directory.
> vscode: update ada.projectFile setting

- testsuite/tests/name_resolution/iterated_component_association/iterassoc.adb
- testsuite/tests/name_resolution/iterated_component_association/iterassoc.ads
- testsuite/tests/name_resolution/iterated_component_association/test.out
- testsuite/tests/name_resolution/iterated_component_association/test.yaml
> Add some tests for `IteratedAssoc` name resolution

- ada/ast.py
- testsuite/tests/name_resolution/index_attr/index.ads
- testsuite/tests/name_resolution/index_attr/test.out
- testsuite/tests/name_resolution/index_attr/test.yaml
- user_manual/changes/UC02-026.yaml
> Add Ada 2022 `'Index` attribute nameres support

- ada/ast.py
- testsuite/tests/properties/is_constant_object/constant.adb
- testsuite/tests/properties/is_constant_object/constant.ads
- testsuite/tests/properties/is_constant_object/renam.adb
- testsuite/tests/properties/is_constant_object/renam.ads
- testsuite/tests/properties/is_constant_object/test.out
- testsuite/tests/properties/is_constant_object/test.yaml
- user_manual/changes/U330-040.yaml
> Add `is_constant_object` property

- ada/ast.py
- ada/grammar.py
- testsuite/tests/name_resolution/no_type_object_renaming_decl/proc.adb
- testsuite/tests/name_resolution/no_type_object_renaming_decl/test.out
- testsuite/tests/name_resolution/no_type_object_renaming_decl/test.yaml
- testsuite/tests/properties/is_constant_object/renam.adb
- testsuite/tests/properties/is_constant_object/renam.ads
- testsuite/tests/properties/is_constant_object/test.out
- user_manual/changes/UC08-034.yaml
> Make subtype_mark optional in object renames

- ada/ast.py
- testsuite/tests/properties/is_constant_object/accessconst.adb
- testsuite/tests/properties/is_constant_object/choice.adb
- testsuite/tests/properties/is_constant_object/constant.adb
- testsuite/tests/properties/is_constant_object/discr.adb
- testsuite/tests/properties/is_constant_object/ers.adb
- testsuite/tests/properties/is_constant_object/index.ads
- testsuite/tests/properties/is_constant_object/loops.adb
- testsuite/tests/properties/is_constant_object/protect.adb
- testsuite/tests/properties/is_constant_object/protect.ads
- testsuite/tests/properties/is_constant_object/qual.adb
- testsuite/tests/properties/is_constant_object/test.out
- testsuite/tests/properties/is_constant_object/test.yaml
- testsuite/tests/properties/is_constant_object/view.adb
- user_manual/changes/U330-040.yaml
> Improve `is_constant_object` property support

- ada/ast.py
- testsuite/tests/name_resolution/stable_properties/stable.adb
- testsuite/tests/name_resolution/stable_properties/stable.ads
- testsuite/tests/name_resolution/stable_properties/tag.ads
- testsuite/tests/name_resolution/stable_properties/test.out
- testsuite/tests/name_resolution/stable_properties/test.yaml
- user_manual/changes/V106-012.yaml
This change adds support for the `Stable_Properties` aspect introduced
by Ada 2022 standard revision.
> Add `Stable_Properties` aspect support

- user_manual/ada_api_tutorial.rst
The proposed changes resolve compilation issues in the example code.
> Fix Libadalang.Project_Provider examples in Ada API Tutorial
